version: '3.2'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=dbo -user=test_user -password=password -connectRetries=10 migrate
    volumes:
      - ../db_migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nda4M!CC@hbMKlws
    volumes:
      - ./postgres_init/:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 0.5s
      timeout: 25s
      retries: 25